apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service
  labels:
    app: catalog-service
data:
  application.yml: |
    polar:
      greeting: Welcome to the book catalog from Kubernetes!
    spring:
      datasource:
        url: jdbc:postgresql://polar-postgres/polardb_catalog
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-ui: http://polar-keycloak/realms/PolarBookshop
